version: '3.7'
services:
    api:
        build: .
        ports:
            - ${API_PORT}:${API_PORT}
        volumes:
            - ./:/app
        depends_on:
            - mysql
            - redis
        restart: always
    mysql:
        image: mysql:5.6
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            MYSQL_DATABASE: $DB_NAME
            MYSQL_ROOT_PASSWORD: $DB_PASS
    redis:
        image: redis
        ports:
          - 6380:6379
